[Options]
makeflow_type = "analysis"
# path_to_do_scripts = "/home/obs/src/hera_opm/pipelines/h3c/rtp/v1/task_scripts"
path_to_do_scripts = "/users/jsdillon/Libraries/hera_opm/pipelines/h3c/rtp/v1/task_scripts"
source_script = "~/.bashrc"
# conda_env = "RTP"
conda_env = "python3"
# ex_ants_path = "/home/obs/src/hera_opm/pipelines/h3c/rtp/v1/bad_ants"
ex_ants_path = "/users/jsdillon/Libraries/hera_opm/pipelines/h3c/rtp/v1/bad_ants"
base_mem = 8000
base_cpu = 1
# batch_system = "slurm"
# default_queue = "hera,bigmem"
# mandc_report = true
pbs_mail_user = "jsdillon+nrao@berkeley.edu"

[ANT_METRICS_OPTS]
crossCut = 5.0
deadCut = 5.0
extension = ".ant_metrics.hdf5"
vis_format = "uvh5"

[NB_OPTS]
basenbdir = '/home/obs/src/H3C_plots'

[REDCAL_OPTS]
ant_z_thresh = 4.0
solar_horizon = 0.0
nInt_to_load = 8
flag_nchan_low = 0
flag_nchan_high = 0
oc_maxiter = 2000
min_bl_cut = 15
max_bl_cut = 100
iter0_prefix = ".iter0"
good_statuses = "passed_checks,needs_checking,digital_ok,digital_maintenance,calibration_maintenance,calibration_triage,calibration_ok"

[ABSCAL_OPTS]
model_files_glob = "'/lustre/aoc/projects/hera/aewallwi/H3C_analysis/abscal_models/RIMZ_v0/redundant_only/zen*.uvh5'"
nInt_to_load = 60
min_bl_cut = 4.0
max_bl_cut = 100.0
phs_max_iter = 100
phs_conv_crit = 1e-6
edge_cut = 100

[WorkFlow]
actions = ["SETUP", 
           "ANT_METRICS",
           "MAKE_NOTEBOOK",
           "REDCAL",
           "ABSCAL",
           "MAKE_REDCAL_NOTEBOOK"]

[ANT_METRICS]
args = ["{basename}", "${ANT_METRICS_OPTS:crossCut}",
        "${ANT_METRICS_OPTS:deadCut}", "${ANT_METRICS_OPTS:extension}",
        "${ANT_METRICS_OPTS:vis_format}"]


[MAKE_NOTEBOOK]
time_prereqs = "ANT_METRICS"
n_time_neighbors = "all"
args = ["{basename}", "{prev_basename}", "${NB_OPTS:basenbdir}"]


[REDCAL]
prereqs = "ANT_METRICS"
args = ["{basename}", "${Options:ex_ants_path}", "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}", "${REDCAL_OPTS:flag_nchan_low}",
        "${REDCAL_OPTS:flag_nchan_high}", "${REDCAL_OPTS:oc_maxiter}",
        "${REDCAL_OPTS:nInt_to_load}", "${REDCAL_OPTS:min_bl_cut}",
        "${REDCAL_OPTS:max_bl_cut}", "${REDCAL_OPTS:iter0_prefix}",
        "${ANT_METRICS_OPTS:extension}", "${REDCAL_OPTS:good_statuses}"]

[MAKE_REDCAL_NOTEBOOK]
prereqs = "REDCAL"
time_prereqs = "REDCAL"
n_time_neighbors = "all"
mem = 64000
args = ["{basename}", "{prev_basename}", "${NB_OPTS:basenbdir}"]

[ABSCAL]
prereqs = "REDCAL"
args = ["{basename}", "${ABSCAL_OPTS:model_files_glob}", "${ABSCAL_OPTS:nInt_to_load}",
        "${ABSCAL_OPTS:min_bl_cut}", "${ABSCAL_OPTS:max_bl_cut}", "${ABSCAL_OPTS:phs_max_iter}",
        "${ABSCAL_OPTS:phs_conv_crit}", "${ABSCAL_OPTS:edge_cut}"]
