[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/aewallwi/H3C_analysis/task_scripts"
source_script = "~/.bashrc"
conda_env = "hera3"
ex_ants_path = "/lustre/aoc/projects/hera/aewallwi/H3C_analysis/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"

[XRFI_OPTS]
kt_size = 8
kf_size = 8
sig_init = 5.0
sig_adj = 2.0
#label = "minblcut.40.0.redonly"
label = ""
[XRFI_DAY_THRESHOLD_OPTS]
nsig_f = 7.0
nsig_t = 7.0
nsig_f_adj = 5.0
nsig_t_adj = 5.0

############################################################################################################

[WorkFlow]
actions = ["XRFI_DAY_THRESHOLD"]


[XRFI]
mem = 32000
args = ["{basename}", "${XRFI_OPTS:kt_size}", "${XRFI_OPTS:kf_size}", "${XRFI_OPTS:sig_init}",
        "${XRFI_OPTS:sig_adj}"]

[XRFI_DAY_THRESHOLD]
#prereqs = "XRFI"
#time_prereqs = "XRFI"
#n_time_neighbors = "all"
args = ["{basename}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_f}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_t}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_f_adj}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_t_adj}"]


