# This toml runs omnical using bandants files that drop antennas that were flipped on the `ee` polarization. 
[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/aewallwi/H3C_analysis/task_scripts"
source_script = "~/.bashrc"
conda_env = "hera3"
ex_ants_path = "/lustre/aoc/projects/hera/aewallwi/H3C_analysis/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"

[REDCAL_OPTS]
ant_z_thresh = 1e100#4.0 is the default. 
solar_horizon = 0.0
nInt_to_load = 8
flag_nchan_low = 0#50 was the default
flag_nchan_high = 0#50 was the default
min_bl_cut = 15
max_bl_cut = 900#90 was the default

############################################################################################################

[WorkFlow]
actions = ["REDCAL_NOFLIP_EE"]

[REDCAL_NOFLIP_EE]
args = ["{basename}", "${Options:ex_ants_path}", "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}", "${REDCAL_OPTS:flag_nchan_low}",
        "${REDCAL_OPTS:flag_nchan_high}", "${REDCAL_OPTS:nInt_to_load}",
        "${REDCAL_OPTS:min_bl_cut}", "${REDCAL_OPTS:max_bl_cut}"]
