[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/aewallwi/H3C_analysis/task_scripts"
source_script = "~/.bashrc"
conda_env = "hera3"
ex_ants_path = "/lustre/aoc/projects/hera/aewallwi/H3C_analysis/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"

[ABSCAL_OPTS]
#model_files_glob = "'/lustre/aoc/projects/hera/aewallwi/H3C_analysis/abscal_models/RIMZ_v0/redundant_only/zen.*.uvh5'"
model_files_glob = "'/lustre/aoc/projects/hera/aewallwi/H3C_analysis/abscal_models/RIMZ_v0/all_bls/zen.*.uvh5'"
nInt_to_load = 6
min_bl_cut = 1.0
max_bl_cut = 100.0
phs_max_iter = 100
phs_conv_crit = 1e-6
edge_cut = 100
refant = 12
#label = "redonly"

[XRFI_OPTS]
kt_size = 8#originally 8
kf_size = 8#originally 8
sig_init = 8.0#originally 5
sig_adj = 5.0#originally 2

[XRFI_DAY_THRESHOLD_OPTS]
nsig_f = 7.0#orginally 7
nsig_t = 7.0#originally 7
nsig_f_adj = 5.0#originally 3
nsig_t_adj = 5.0#originally 3


############################################################################################################

[WorkFlow]
actions = ["ABSCAL", "XRFI", "XRFI_DAY_THRESHOLD"]
#actions = ["XRFI_LABEL", "XRFI_DAY_THRESHOLD"]
#actions = ["XRFI_DAY_THRESHOLD"]
[ABSCAL]
args = ["{basename}", "${ABSCAL_OPTS:model_files_glob}", "${ABSCAL_OPTS:nInt_to_load}",
        "${ABSCAL_OPTS:min_bl_cut}", "${ABSCAL_OPTS:max_bl_cut}", "${ABSCAL_OPTS:phs_max_iter}",
        "${ABSCAL_OPTS:phs_conv_crit}", "${ABSCAL_OPTS:edge_cut}", "${ABSCAL_OPTS:refant}"]

[XRFI]
#prereqs = "ABSCAL_LABELED_REDONLY"
mem = 32000
args = ["{basename}", "${XRFI_OPTS:kt_size}", "${XRFI_OPTS:kf_size}", "${XRFI_OPTS:sig_init}",
        "${XRFI_OPTS:sig_adj}"]

[XRFI_DAY_THRESHOLD]
prereqs = "XRFI"
time_prereqs = "XRFI"
n_time_neighbors = "all"
args = ["{basename}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_f}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_t}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_f_adj}", "${XRFI_DAY_THRESHOLD_OPTS:nsig_t_adj}"]
