[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/aewallwi/H3C_analysis/task_scripts"
source_script = "~/.bashrc"
conda_env = "hera3"
ex_ants_path = "/lustre/aoc/projects/hera/aewallwi/H3C_analysis/bad_ants"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"

############################################################################################################

[WorkFlow]
actions = ["EXTRACT_AUTOS"]

[EXTRACT_AUTOS]
args = ["{basename}"]


